Fixed use of TIOCSTI on Linux 6.2 or higher

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -45,7 +45,13 @@ jobs:
       run: sudo gem install coveralls-lcov
 
     - name: Build with with gcov
-      run: script -q -e -c 'ls -al "/proc/$$/fd/"; echo "----"; tty; echo "----"; stty -a; echo "----"; infocmp; echo "----"; ./build.sh coverage'
+      run: |
+        ls -al /proc/sys/dev/tty/legacy_tiocsti
+        echo "1" > /proc/sys/dev/tty/legacy_tiocsti 2>/dev/null || true # Required for Linux 6.2.0 or later
+        echo "/proc/sys/dev/tty/legacy_tiocsti"
+        cat /proc/sys/dev/tty/legacy_tiocsti
+        sysctl -w dev.tty.legacy_tiocsti=1
+        script -q -e -c './build.sh coverage'
 
     - name: Generate lcov.info and publish to coveralls.io
       run: |
diff --git a/.github/workflows/coverity-scan.yml b/.github/workflows/coverity-scan.yml
--- a/.github/workflows/coverity-scan.yml
+++ b/.github/workflows/coverity-scan.yml
@@ -76,6 +76,9 @@ jobs:
 
     - name: Make unit test
       run: |
+	setcap cap_sys_admin+ep test/.libs/eventloop_monitor_test
+	getcap test/.libs/eventloop_monitor_test
+        echo "1" > /proc/sys/dev/tty/legacy_tiocsti 2>/dev/null || true # Required for Linux 6.2 or later
         script -q -e -c 'make check' && RET=$? || RET=$?
         cat test/*.log || echo
         echo "Exit status: $RET"
